on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: ${{ secrets.source_repo }}
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
